volumes:
  pdf_web_local_postgres_data: {}
  pdf_web_local_postgres_data_backups: {}
  pdf_web_local_redis_data: {}
  stirling_data:
  stirling_config:


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: pdf_web_local_django
    container_name: pdf_web_local_django
    depends_on:
      - postgres
      - redis
      - mailpit
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    ports:
      - '8000:8000'
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: pgvector/pgvector:pg16
    container_name: pdf_web_local_postgres
    volumes:
      - pdf_web_local_postgres_data:/var/lib/postgresql/data
      - pdf_web_local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres

  mailpit:
    image: docker.io/axllent/mailpit:latest
    container_name: pdf_web_local_mailpit
    ports:
      - "8025:8025"

  redis:
    image: docker.io/redis:6
    container_name: pdf_web_local_redis

    volumes:
      - pdf_web_local_redis_data:/data


  celeryworker:
    <<: *django
    image: pdf_web_local_celeryworker
    container_name: pdf_web_local_celeryworker
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *django
    image: pdf_web_local_celerybeat
    container_name: pdf_web_local_celerybeat
    depends_on:
      - redis
      - postgres
      - mailpit
    ports: []
    command: /start-celerybeat

  stirling-pdf:
    image: frooodle/s-pdf:0.29.0
    container_name: pdf_web_stirling
    ports:
      - "8090:8080"
    volumes:
      - stirling_data:/usr/share/tessdata
      - stirling_config:/configs
    environment:
      - DOCKER_ENABLE_SECURITY=false
      - SYSTEM_DEFAULTLOCALE=en-US
      - INSTALL_BOOK_AND_ADVANCED_HTML_OPS=true
    restart: unless-stopped
    networks:
      - default
#
#  flower:
#    <<: *django
#    image: pdf_web_local_flower
#    container_name: pdf_web_local_flower
#    ports:
#      - '5555:5555'
#    command: /start-flower
